repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
      - id: ruff-format

  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: bash -c 'cd web && npm run lint'
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false

      - id: typescript
        name: typescript
        entry: bash -c 'cd web && npm run type-check'
        language: system
        types_or: [javascript, jsx, ts, tsx]
        pass_filenames: false
