[[policies]]
name = "Daily Photos"
account = "demo@icloud.com"
album = "All Photos"
directory = "~/Photos/Daily"

[[policies]]
name = "Favorites Backup"
account = "demo@icloud.com"
album = "Favorites"
directory = "~/Photos/Favorites"
