[[policy]]
name = "Daily Photos"
username = "demo@icloud.com"
album = "All Photos"
directory = "~/Photos/Daily"

[[policy]]
name = "Favorites Backup"
username = "demo@icloud.com"
album = "Favorites"
directory = "~/Photos/Favorites"
