import { Metadata } from 'next'
import { Providers } from './providers'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body style={{ margin: 0, backgroundColor: '#F7FAFC' }}>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
