[[policy]]
name = "Test Policy"
username = "meuryuuki@gmail.com"
directory = "/mnt/crucial/Shared/test/"
album = "Twitter"
library = "Personal Library"


[[policy]]
name = "Favorites Backup"
username = "demo@icloud.com"
directory = "~/Photos/Favorites"
